### ISSUE TITLE
What is the camera convention? What does the camera coordinate system look like? 

### ISSUE THREAD

**Issue by scy639** [nianticlabs/map-free-reloc#10]
Hi! thanks for your great work!
The README.md says:
> The pose is given in world-to-camera format, i.e. $R(q), t$ transform a world point $p$ to the camera coordinate system as $Rp + t$.

But what does the camera coordinate system look like? In detail, what is the direction of x,y,z axis of camera?

**Comment by eduardohenriquearnold** [comment]
Hi, thanks for your question. The camera follows the OpenCV convention: X right, Y down, Z forward.

**Comment by scy639** [comment]
Thanks so much!
