### ISSUE TITLE
Difference with a SLAM system?

### ISSUE THREAD

**Issue by sithu31296** [nianticlabs/map-free-reloc#16]
From a high level, what is the difference between map-free relocalization and a SLAM system? From my understanding, a SLAM system estimates the relative pose to a map and a map-free relocalization task estimates the metric relative pose to a reference image. Is this correct? Both methods also incrementally build a map from estimated camera poses. If this is incorrect, please let me know.

**Comment by ebrach** [comment]
Hi, 

* SLAM is the problem of building a map from a stream of image inputs.
* Map-free relocalisation is the problem of estimating a metric relative pose between two images.

A SLAM system builds a map. A map-free relocalisation system does not build a map - map-free relocalisation is stateless. It takes two images and predicts the relative pose. It does so independently for all pairs of inputs - it does not remember what it has seen earlier.

Best,
Eric
