### ISSUE TITLE
question about colmap scenes

### ISSUE THREAD

**Issue by samwli** [nianticlabs/map-free-reloc#17]
Hello, thanks for all the work on this dataset! I just have a question about the colmap models for the train scenes, and `overlaps.npz`. 

It seems to me that each scene is split into 2 colmaps, from seq0 images and seq1 images. Within a sequence, it's easy to get correspondences from the colmap model. However, overlaps.npz also gives overlaps between frames across sequences. Is my understanding of the dataset correct? If so, is there a way to get correspondences between a frame from seq0 and a frame from seq1? Thanks for the help!

**Comment by jamiewynn** [comment]
Hi Sam, thanks for your question. Your understanding of the dataset is right. For that reason I'm afraid there isn't a way to get correspondences across the two sequences, but only within a sequence.

Best wishes,
Jamie Wynn

**Comment by samwli** [comment]
Hi Jamie, 

Thanks for your reply! One more question, are the 3D points in the colmap models metric?

Thanks,
Sam

**Comment by jamiewynn** [comment]
Hi Sam,

Yes they are :)

Best,
Jamie
