### ISSUE TITLE
Reproduce the results on 7scenes dataset

### ISSUE THREAD

**Issue by MisEty** [nianticlabs/map-free-reloc#2]
Hi
Thanks for your greate work! I want to reproduce the results on 7scenes dataset but there are many config settings and I am a little confused. How can I run as the paper, e.g. using all mapping frames and get the results in Figure 6?

Best regards,
Peng

**Comment by eduardohenriquearnold** [comment]
Hi @MisEty . You can find a comprehensive guide in the [7Scenes benchmark evaluation section](https://github.com/nianticlabs/map-free-reloc/blob/main/benchmark/extended_datasets.md#-7scenes-visual-localisation-evaluation). 

For feature matching baselines you will need to download the pairs indices, feature matches and estimated depthmaps, as detailed [here](https://github.com/nianticlabs/map-free-reloc/blob/main/benchmark/extended_datasets.md#7scenes). For RPR baselines you can download our pre-trained models (trained on Scannet), as detailed [here](https://github.com/nianticlabs/map-free-reloc#pre-trained-models).

To get the results in Table 6, you can use the command template provided [here](https://github.com/nianticlabs/map-free-reloc/blob/main/benchmark/extended_datasets.md#-7scenes-visual-localisation-evaluation). You will use the configurations from [config/matching/sevenscenes](https://github.com/nianticlabs/map-free-reloc/tree/main/config/matching/sevenscenes ) and [config/regression/scannet](https://github.com/nianticlabs/map-free-reloc/tree/main/config/regression/scannet), for matching and regression baselines, respectively.  You'll also need use the appropriate flags: `--one_nn` for RPR and feature matching and `--triang` for pose triangulation.

Note that the regression baselines evaluated on 7Scenes were trained on Scannet, thus why the latter folder is called Scannet.

**Comment by MisEty** [comment]
Thanks for your help! I will try to evaluate on 7scenes and update my results.

**Comment by eduardohenriquearnold** [comment]
I'll close this issue for now. Feel free to reopen or create a new one in case you have more questions.
