### ISSUE TITLE
Why are intrinsics not shared in sequence?

### ISSUE THREAD

**Issue by Parskatt** [nianticlabs/map-free-reloc#5]
![image](https://github.com/nianticlabs/map-free-reloc/assets/22053118/661a45ed-2321-43d0-8168-c784868ac801)
For example, this is for s00535. It seems strange to me that the camera parameters are not consistent, since it seems to be the same camera taking the images? The variation is quite small, and as I've understood the evaluation thresholds are mild so maybe exact ground truth is not that important, still interested in the reasoning though.

**Comment by amonszpart** [comment]
The images were recorded with an iPhone using ARKit.
ARKit enables autofocus by default, and we did not find a way at the time to disable it.
This means every frame could be slightly zoomed in, yielding a change in the focal length.
The variations in focal length are quite small, but we think the exact values are needed for the best results.

It's a bit of overhead to use in code, I know, but how fun to know that you are doing everything you can to squeeze out every last digit of accuracy?! :)
