### ISSUE TITLE
"File is an invalid type" (yes, yet another issue, sorry)

### ISSUE THREAD

**Issue by Parskatt** [nianticlabs/map-free-reloc#6]
![image](https://github.com/nianticlabs/map-free-reloc/assets/22053118/cc442083-ee4d-4ae9-a6fe-6551fddda062)
In uploading my solution [to the submission site](https://research.nianticlabs.com/mapfree-reloc-benchmark/submit), generated by running [submission.py](submission.py), the above error is raised.
I'm pretty sure the file uploaded is correctly formatted.

In case I've done something stupid, I've also uploaded the submission so you can check if its somehow weird
[submission.zip](https://github.com/nianticlabs/map-free-reloc/files/11829690/submission.zip)

**Comment by eduardohenriquearnold** [comment]
Thanks for reporting this issue. We're verifying this problem with our web team and will update the progress here.

**Comment by eduardohenriquearnold** [comment]
@Parskatt it seems this problem has been solved by our web team. I tried submitting your file and it worked for me, could you please try again? Thanks

**Comment by Parskatt** [comment]
@eduardohenriquearnold yes it works, thanks.
Also check out our results, they're quite good :)

**Comment by eduardohenriquearnold** [comment]
That's great, very nice results - can't wait to learn more about your method! Thanks for contributing! :)
