### ISSUE TITLE
Website Submission Results not Processing

### ISSUE THREAD

**Issue by crockwell** [nianticlabs/map-free-reloc#7]
Hello,

I've made a private submission to the website, uploaded two days ago. It still says "processing" under status. This is surprising since the page indicates the results should be ready within a few minutes. Could someone please assist with this? It is for an upcoming deadline.

Thanks so much!
Chris

**Comment by eduardohenriquearnold** [comment]
Hi, thanks for reporting this, we are investigating the issue and will report soon, but likely on Monday.

**Comment by crockwell** [comment]
Thank you Eduardo! Also, thanks for the cool dataset. It has been fun to use and the code is very clean!

**Comment by crockwell** [comment]
As messaged via email, it seemed I had a tensor as part of my submission file, causing a silent failure. After changing this tensor to an int, the evaluation worked quickly. Thanks Eduardo!
