### ISSUE TITLE
how to use the pipeline on own dataset

### ISSUE THREAD

**Issue by Gotta-C** [nianticlabs/map-free-reloc#8]

**Comment by Gotta-C** [comment]
after download correspondences and depth files, lack of 'data/mapfree/val/s00460/poses.txt'

**Comment by Gotta-C** [comment]
I have get the relative pose, how to visual pose using drawFrameAxes for AR marker. the pose to 4*4 matrix and decompose rvec and tvec. if I use the template image as a marker, the tvec is not correlation to template center

**Comment by eduardohenriquearnold** [comment]
Hello, I am not sure I understand your question. Can you please clarify?

**Comment by Gotta-C** [comment]
> Hello, I am not sure I understand your question. Can you please clarify?

I have capture a video about a painting hanging on the wall，then use the first frame as a marker which is seq0，total frames  in seq1. calculate all seq1 frame poses using submission.py and trans to 4*4 matrix. the first frame pose multiply its inv to get an Identity matrix, and other frames multiply first frame pose inv to get the relative pose as first frame. Finally I want to visual poses on images, decompose the rvec and tvec from 4*4 matrix, visualized result the rvec is right, but tvec not.

**Comment by Gotta-C** [comment]
What device did you use to capture the video？I used my phone and changed different intrinsics fx, fy,  the RPR inference result is not changed
