### ISSUE TITLE
Submission results

### ISSUE THREAD

**Issue by Gotta-C** [nianticlabs/map-free-reloc#9]
I use 3d3d method with or without dptkitti to run the submission.py on test dataset and modify ESTIMATED_DEPTH: dptkitti in mapfree.yaml
python submission.py config/regression/mapfree/3d3d.yaml --checkpoint mapfree/3d3d.ckpt --split test -o results/

and submit, but get same result.
![image](https://github.com/nianticlabs/map-free-reloc/assets/20768683/c8d7819a-d15a-44ee-89c4-ee0b69e15830)

**Comment by eduardohenriquearnold** [comment]
The RPR family of methods (which 3d3d is a variant of) do not use estimated depth maps, they must recover the scale within the model itself and thus why it doesn't make any difference if you change the `ESTIMATED_DEPTH` parameter for those models.
Feel free to reopen this if you need further clarification.
